services:
  redis:
    image: redis:alpine
    networks:
      - django-network
  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - django-network
  celery:
    build: .
    command: celery -A myapp worker --loglevel=info
    depends_on:
      - redis
      - django
    networks:
      - django-network
networks:
  django-network:
    driver: bridge