services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
      - "8083:8080"
    depends_on:
      - postgres
volumes:
  postgres-data: