services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - voting-network
  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - voting-network
  redis:
    image: redis:alpine
    networks:
      - voting-network
  worker:
    image: dockersamples/examplevotingapp_worker
    depends_on:
      - redis
      - db
    networks:
      - voting-network
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voting_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - voting-network
volumes:
  db-data:
networks:
  voting-network:
    driver: bridge